version: '3'

services:
  fe:
    container_name: test-deploy-fe
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
